add_newline = false

format = """
[░▒▓](#a3aed2)\
[ 󰌽 ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$python\
$terraform\
$aws\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

# format = """$directory$character"""

# right_format = """$nodejs$python$terraform$aws"""

[directory]
truncate_to_repo = false
truncation_length = 0
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_symbol = "…/"

[aws]
symbol = " 󰸏 "
format = '[$symbol($profile)]($style)'

[aws.profile_aliases]
"Development/AdministratorAccessV2" = "dev"
"Production/AdministratorAccessV2" = "prod"
"Captains-eye/AdministratorAccessV2" = "mgmt"
"Finance/AdministratorAccessV2" = "fin"
"AI/AdministratorAccess" = "ai"

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[terraform]
symbol = " 󱁢 "
format ='[$symbol$version]($style) ' 

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
