lastupdatecheck: 0
recentrepos:
- /home/felix/workspace/terraform-modules/ecs-service
- /home/felix/workspace/dotfiles
- /home/felix/workspace/devops/captain-infra
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
