import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.95
dynamic_padding = false
decorations = "none"
startup_mode = "Maximized"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 5
y = 5

[scrolling]
history = 100000
multiplier = 3

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "IosevkaTerm Nerd Font Mono"

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"
